name = ''                           # (1)
while name != 'Berry':          # (2)
    print('Please type your name.')
    name = input()                  # (3)
print('Thank you!')                 # (4)
